from dataclasses import dataclass, field
from typing import Any


class ReasoningError(Exception):
    """Base exception for reasoning provider operations."""

    pass


@dataclass
class ReasoningRequest:
    """Input payload for a reasoning/extraction request."""

    document_id: str
    pages: list[dict[str, Any]]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RawExtractedParty:
    name: str
    role: str
    page_number: int
    source_span: str


@dataclass
class RawExtractedClause:
    clause_identifier: str
    title: str
    category: str
    text: str
    page_start: int
    page_end: int
    source_span: str


@dataclass
class RawExtractedObligation:
    obligor: str
    duty: str
    trigger: str | None
    deadline: str | None
    page_start: int
    page_end: int
    source_span: str
    related_clause_identifier: str | None = None


@dataclass
class RawExtractedDate:
    date_type: str
    raw_text: str
    normalized_date: str | None
    description: str
    page_number: int
    source_span: str


@dataclass
class RawExtractedReviewFlag:
    flag_type: str
    title: str
    description: str
    severity: str
    page_start: int
    page_end: int
    source_span: str
    related_clause_identifier: str | None = None


@dataclass
class RawExtractionResult:
    """Structured extraction output produced by a reasoning provider."""

    parties: list[RawExtractedParty] = field(default_factory=list)
    clauses: list[RawExtractedClause] = field(default_factory=list)
    obligations: list[RawExtractedObligation] = field(default_factory=list)
    dates: list[RawExtractedDate] = field(default_factory=list)
    review_flags: list[RawExtractedReviewFlag] = field(default_factory=list)
    provider_info: dict[str, Any] = field(default_factory=dict)


@dataclass
class QAReasoningRequest:
    """Input payload for a grounded Q&A reasoning request."""

    document_id: str
    question: str
    context_chunks: list[dict[str, Any]]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RawAnswerClaim:
    """Individual claim generated by the reasoning provider for Q&A."""

    claim_text: str
    claim_type: str = "document_fact"
    page_start: int | None = None
    page_end: int | None = None
    source_span: str | None = None
    section: str | None = None
    clause_id: str | None = None


@dataclass
class RawQAResult:
    """Grounded Q&A output produced by a reasoning provider."""

    answer_text: str
    claims: list[RawAnswerClaim] = field(default_factory=list)
    general_information: str | None = None
    requires_professional_review: bool = False
    provider_info: dict[str, Any] = field(default_factory=dict)


@dataclass
class BriefReasoningRequest:
    """Input payload for a brief questions generation reasoning request."""

    document_id: str
    parties: list[dict[str, Any]] = field(default_factory=list)
    clauses: list[dict[str, Any]] = field(default_factory=list)
    obligations: list[dict[str, Any]] = field(default_factory=list)
    dates: list[dict[str, Any]] = field(default_factory=list)
    review_flags: list[dict[str, Any]] = field(default_factory=list)
    qa_findings: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RawBriefQuestion:
    """Single neutral question for a legal professional."""

    question: str
    category: str = "general"
    rationale: str | None = None
    related_clause_id: str | None = None


@dataclass
class RawBriefQuestionsResult:
    """Structured question preparation output produced by a reasoning provider."""

    questions: list[RawBriefQuestion] = field(default_factory=list)
    facts_to_confirm: list[str] = field(default_factory=list)
    documents_to_bring: list[str] = field(default_factory=list)
    open_questions: list[str] = field(default_factory=list)
    provider_info: dict[str, Any] = field(default_factory=dict)
